### ISSUE TITLE
Maintaining order

### ISSUE THREAD

**Issue by nandanrao** [jonkemp/gulp-useref#104]
I might be totally missing something, but it would seem that the order of files read from html blocks is not maintained, which causes problems in my case where the dependency resolution and ordering done by plugins such as wiredep is necessary for the app to work properly! 

Here's another example of someone with the same problem using useref for injecting bower files, starting from the gulp-angular-generator: https://github.com/auth0/lock/issues/111

Am I missing some way to maintain order in the concatenated file, or is that simply not a useref feature at this point? Should it be one? Is anyone else running into this issue?

**Comment by jonkemp** [comment]
Not sure. You can see here

https://github.com/jonkemp/gulp-useref/blob/master/index.js#L105

that `nosort` is set to `true` which is passed to [node-glob](https://github.com/isaacs/node-glob#options) through `vinyl-fs` which tells it not to change the order of the files.

**Comment by jbblanchet** [comment]
A quick test shows the order is preserved:

```html
<!-- build:js scripts/combined.js -->
<script src="3/3.js"></script>
<script src="1.js"></script>
<script src="2/2.js"></script>
<!-- endbuild -->
```

outputs the following combined.js:
```javascript
console.log(3);
console.log(1);
console.log(2);
```

Could it be a problem with wiredep? Do you have a specific example of the order not working?

(I'm interested because my proposal for adding asset streams #116 currently doesn't preserve order, so I'll have to look into it anyway)

**Comment by jonkemp** [comment]
Closing.
