### ISSUE TITLE
How specify scripts folder if views and scripts in the separate folder

### ISSUE THREAD

**Issue by Mirodil** [jonkemp/gulp-useref#106]
scripts did not outputting if i have the following folder structure:
```
project
--- Views
------ Search
--------- Index.html
--- Scripts
------ angular
------ app
--- gulpfile.js
```
and inside `index.html` has:
``` html
<html>
....
<body>
    <!-- build:js /scripts/app.js -->
    <script src="/scripts/fotorama/fotorama.js"></script>
    <script src="/scripts/jquery/jquery.dropdownlist.js"></script>   
    <!-- endbuild -->
</body>
</html>
```
and `gulpfile.js`:
```javascript
var gulp = require('gulp'),
	useref = require('gulp-useref');
 
gulp.task('default', function () {
	var assets = useref.assets();
	
	return gulp.src('Views/**/*.cshtml')
		.pipe(assets)
		.pipe(assets.restore())
		.pipe(useref())
		.pipe(gulp.dest('dist'));
});
```

**Comment by jonkemp** [comment]
May be related to this jonkemp/gulp-useref/issues/118.

**Comment by manuel-di-iorio** [comment]
I'm wondering too if this is possible.
In gulp-usemin I can use the "outputRelativePath" option to specify a different path for the compiled assets (js, css) relative to the html sourcefile path.

Any option here? Thanks

Another related issue: https://github.com/jonkemp/gulp-useref/issues/87

**Comment by jonkemp** [comment]
There's now a base option to specify the output folder relative to the cwd.

https://github.com/jonkemp/gulp-useref#optionsbase
