### ISSUE TITLE
Option to place assets inline

### ISSUE THREAD

**Issue by nmec** [jonkemp/gulp-useref#107]
Would it be possible to place elements inline, rather than as separate resources? For example:

```html
<html>
<head>
    <!-- build:css inline -->
    <link href="css/critical.css" rel="stylesheet">
    <!-- endbuild -->
</head>
<body>
    <!-- build:js inline -->
    <script type="text/javascript" src="scripts/critical.js"></script>
    <!-- endbuild -->
</body>
</html>
```

Would output:

```html
<html>
<head>
	<style>
		html { box-sizing: border-box; }
	</style>
</head>
<body>
	<script>
		document.documentElement.className = document.documentElement.className.replace("no-js","js");
	</script>
</body>
</html>
```

This would solve use cases where you want critical code loaded as soon as possible or for single page apps that serve the same page for all requests and you can save yourself the additional requests for external resources.

**Comment by jonkemp** [comment]
You can use gulp-inline-css for that. I'm pretty sure there is a gulp plugin for critical css as well.

**Comment by nmec** [comment]
Thanks for pointing out `gulp-inline-css`. Would it be a significant change to implement inline functionality in this lib?

**Comment by jonkemp** [comment]
It would be a significant change and if it can be done with existing plugins in gulp, that's the way it should be done. Gulp.js plugins are usually small and should only do one thing. Adding in a lot of functionality violates that principle.

**Comment by Quirksmode** [comment]
Also really need this feature, is gulp-inline-css definitely the right tool for JS? How can it be combined with gulp-useref to print the JS inline instead of referencing a combined JS file in the html?

**Comment by jonkemp** [comment]
No gulp-inline-css only handles inlining of CSS. You would have to look for another gulp plugin that would handle the javascript inlining.
