### ISSUE TITLE
How to properly inject bower_dependencies (jQuery) using useref

### ISSUE THREAD

**Issue by mariocatch** [jonkemp/gulp-useref#109]
I have a reddit thread here with my question: [reddit link](http://www.reddit.com/r/webdev/comments/36kvk8/gulp_bower_im_having_some_issues_with_a_core/)

Essentially, I'm not figuring out a viable way to inject my bower_components (jQuery in this case) into my final index.html file, based on the snippets I've included in the source index.html file. Seems no matter what I try in the source html file, nothing is injected/placed in the final output of that file.

The reddit thread has the information, but for the most part, here's what I've got. I've excluded my attempts at referencing bower_components since they were all to no avail. This is my starting point though:

**source index.html**

    
    <link rel="stylesheet" src="styles/site.scss">
    

    
    <script src="scripts/site.js" type="text/javascript"></script>
    

**gulpfile.js**

    var paths = {
      src: {
        js: mainBowerFiles({
          base: './bower_components',
          filter: '**/*.js',
          includeDev: 'true',
        }).concat(['app/scripts/**/*.js'])
      }
    };

    gulp.task('scripts', function() {
        return gulp.src(paths.src.js)
            .pipe(uglify())
            .pipe(gulp.dest('dist/js'))
            .pipe(reload({stream: true}));
    });

**Comment by jonkemp** [comment]
Wiredep does this. Not gulp-useref.

**Comment by mariocatch** [comment]
I was actually able to solve this with useref. It's probably not as viable as the bower component-specific solutions such as wiredep, but my sandbox repo on github has a working solution of pulling in jquery from a bower component, and injecting the proper build path to my index.html using the proper markup that useref expects.
