### ISSUE TITLE
Please create a new release

### ISSUE THREAD

**Issue by Burgov** [jonkemp/gulp-useref#110]
This commit allows me to build sourcemaps: https://github.com/jonkemp/gulp-useref/commit/0f8088e9f8ad156363cfff86a541bc058e03d085 but it's currently only in master branch

**Comment by jonkemp** [comment]
There has been a release since that change was made. Version 1.1.2 is available on npm.

https://www.npmjs.com/package/gulp-useref

**Comment by Burgov** [comment]
Ah you're right, sorry. I was just looking at the tags in this repository, which put me on the wrong foot :)
