### ISSUE TITLE
Auto-detect JS/CSS using "build:all"

### ISSUE THREAD

**Issue by mudcube** [jonkemp/gulp-useref#114]
What do you think about having a new type "all" that auto-detects CSS/JS?
```
<!-- build:all js=js/combined.js css=css/combined.css -->
<link href="some-module.css" />
<script src="some-module.js"></script>
...
<!-- endbuild -->
```

**Comment by jonkemp** [comment]
I don't see the point. Either way it would have to be done through the user module. Maybe you can propose this there.

https://github.com/digisfera/useref

**Comment by mudcube** [comment]
The point is sometimes you don't want to have all your CSS grouped on the top of the document, and all the JS in another section. Example: You're including multiple modules that have both a CSS package and a JS package; it's nice to have the files grouped next to each-other in the code. This is especially nice for larger projects. Thanks for pointing me in the right direction.
