### ISSUE TITLE
How to configure sourcemaps support?

### ISSUE THREAD

**Issue by fedotxxl** [jonkemp/gulp-useref#115]
Hello. How can I achieve following features:

1. concat (join files if I correctly understand it)
2. rev (add hash to the filename)
3. uglify
4. sourcemaps support which will lead me to **ORIGINAL** (not joined) js files 

I spent 2 hours but didn't find an answer =(

**Comment by fedotxxl** [comment]
So can someone help me with this problem?

**Comment by SargoDarya** [comment]
Hanging on the same problem.

**Comment by fedotxxl** [comment]
Hi. Looks like I solved it - check my test repository - https://github.com/fedotxxl/gulp-full

**Comment by jonkemp** [comment]
Can you tell us how you solved it?

**Comment by fedotxxl** [comment]
I'm not sure how it works (I hope it works) - just found solution on github. Created gist - https://gist.github.com/fedotxxl/127c17ccd953dadebbc9

You can try it:
```` 
npm install
gulp build.prod --minify 
cd ./build/js/compiled/

**Comment by jonkemp** [comment]
Here's the useref task from the above repo.

```js
gulp.task("useref", function () {
    var options = {
        searchPath: paths.assets.src
    };

    var sourceMapsWriteOptions = {
        sourceRoot: "/sources/does-not-matter/",
        includeContent: false
    };

    var cssFilter = $.filter("**/*.css");
    var jsFilter = $.filter("**/*.js");
    var assets = $.useref.assets(options, lazypipe().pipe($.sourcemaps.init, {loadMaps: true}));

    var stream = gulp
        .src(_.pathAny(paths.src, "html"))
        .pipe(_.extendHtml()())
        .pipe(assets);

    var processJs = lazypipe()
        .pipe($.ngAnnotate, {gulpWarnings: false})
        .pipe($.uglify);

    if (_.isEnv("minify")) {
        stream = stream
            .pipe($.if("*.js", processJs()))
            .pipe($.if("*.css", $.minifyCss()))
            .pipe($.rev())
            .pipe($.if("*.js", $.sourcemaps.write(".", sourceMapsWriteOptions)));
    }

    return stream
        .pipe(assets.restore())
        .pipe($.useref())
        .pipe($.revReplace())
        .pipe(gulp.dest(paths.target.root))
});
```

**Comment by fedotxxl** [comment]
It doesn't work with gulp-minify-css (may be because of this issue - https://github.com/murphydanger/gulp-minify-css/issues/113)

**Comment by Nijikokun** [comment]
But how to do this with less?
