### ISSUE TITLE
Missing css files

### ISSUE THREAD

**Issue by rbatllet** [jonkemp/gulp-useref#117]
When I exec the first time, it saves the following files: "scripts.js", "vendor.js" and "vendor.css" but "main.css" is missing. But when I exec again, "main.css" is saved!

I'm using this task:

```
gulp.task('compress', function() {
  gulp.src(appConfig.app + '/index.html')
    .pipe(useref.assets())
    .pipe(gulpif('*.js', uglify({
      mangle: false
    })))
    .pipe(gulpif('*.css', minifyCss()))
    .pipe(gulp.dest(appConfig.dist));
});
```

`I'm using version 1.2.0`

**Comment by jonkemp** [comment]
Can you try the latest version from npm or clone this repo and link it to your project to test it?

**Comment by rbatllet** [comment]
It seems it does work with the version 1.3.0 correctly
