### ISSUE TITLE
Async Scripts

### ISSUE THREAD

**Issue by Snugug** [jonkemp/gulp-useref#119]
`async`ing JS is an important part of performance (`defer` too). I'd love to be able to specify that a final asset should be `async` or `defer` (or both).

**Comment by jonkemp** [comment]
`async` is supported.

**Comment by Snugug** [comment]
How do I signal that I'd like something `async`? I couldn't find any documentation discussing that.

**Comment by jonkemp** [comment]
Use the `async` property on the script tag just like you normally would.

**Comment by Snugug** [comment]
I've got `async` and `defer` on all of the script tags I want to combine and they don't come out in the final HTML. Here's the code I'm using:

```html
<!-- build:js /js/foo.js -->
  <!-- Put JS here -->
  <script async defer src="/bower_components/prism/prism.js"></script>
  <script async defer src="/bower_components/prism/components/prism-css.js"></script>
  <script src="/bower_components/prism/components/prism-css-extras.js"></scrip async defert>
  <script async defer src="/bower_components/prism/components/prism-scss.js"></script>
  <script async defer src="/bower_components/prism/components/prism-bash.js"></script>
  <script async defer src="/bower_components/prism/components/prism-markup.js"></script>
  <script async defer src="/bower_components/prism/components/prism-javascript.js"></script>
  <script async defer src="/js/app.js"></script>
  <!-- endbuild -->
```

```javascript
  //////////////////////////////
  // Encapsulate task in function to choose path to work on
  //////////////////////////////
  var UseminTask = function (path) {
    var assets = useref.assets();

    return gulp.src(path)
      .pipe(assets)
      .pipe(gulpif('*.js', uglify()))
      .pipe(gulpif('*.css', minifyCSS()))
      .pipe(assets.restore())
      .pipe(useref())
      .pipe(gulp.dest('.dist/'));
  }

  //////////////////////////////
  // Core Task
  //////////////////////////////
  gulp.task('usemin', function () {
    return UseminTask(UseminPaths);
  });
```

**Comment by jonkemp** [comment]
`async` is supported. I'm not sure about `defer`. Please refer any more questions to the useref repo. That is where the code is that controls this. Looking at the unit tests there, there are tests for `async` but not `defer`.

https://github.com/digisfera/useref

**Comment by Snugug** [comment]
Oh wow! I didn't realize I was on the Gulp repo! Sorry about that!

**Comment by Mode54** [comment]
Here's the solution if anyone stumbles across this...

Add any extra parameters you want to include in the output tag right into the build comment:
```
  <!-- build:js scripts/async.js defer -->
  <script type="text/javascript" src="scripts/three.js"></script> 
  <script type="text/javascript" src="scripts/four.js"></script> 
  <!-- endbuild -->
```

useref repo --> https://github.com/jonkemp/useref/blob/master/README.md
