### ISSUE TITLE
Additional Build Types?

### ISSUE THREAD

**Issue by zellwk** [jonkemp/gulp-useref#121]
I've looked at [#issue 85](https://github.com/jonkemp/gulp-useref/issues/85) but I'm still not sure how to use custom build types yet (especially if I want files to be reved at the same time. 

Currently what I've done is this:

~~~
gulp.task('useref', () => {
  
  var assets = $.useref.assets();

  return gulp.src('./dist/**/*.html')
  .pipe(assets)
  .pipe($.if('*.css', cssPipe()))
  .pipe($.if('*.js', jsPipe()))
  .pipe($.rev())
  .pipe(assets.restore())
  .pipe($.useref({
    uncomment: (content, target, options, alternateSearchPath) => {
      content = content.replace('<!--', '').replace('-->', '');
      return content;
    }
  }))
  .pipe($.revReplace())
  .pipe(gulp.dest('./dist'));
});
~~~

my custom build type (`uncomment`) happens only after `rev()`, and hence I'm not able to rev files within my custom type. 

Is there a way to add custom build types earlier in the pipeline?

**Comment by jonkemp** [comment]
Sorry, but I don't know much about custom blocks. It was implemented in `useref` and then someone else made a pull request here. So my suggestion would be to look here for more information.

https://github.com/jonkemp/gulp-useref/pull/103

Sorry, it took so long for you to get a response.

**Comment by zellwk** [comment]
Okay cool np :) 

Btw, can I email you when I have time to dig into your `gulp.useref` implementation again? I believe the answer lies there, but I'm a little dumbfounded when I tested a month ago.

**Comment by jonkemp** [comment]
:+1:

**Comment by jonkemp** [comment]
Docs on custom build types:

https://github.com/digisfera/useref#custom-blocks

**Comment by jonkemp** [comment]
Closing. If this is still not clear, I'll reopen.
