### ISSUE TITLE
about css replace

### ISSUE THREAD

**Issue by geniuszhe** [jonkemp/gulp-useref#122]
Hi :
   I use the gulp-useref to replace the css like your example  
<pre>
    <span class="pl-c">&lt;!-- build:css css/combined.css --&gt;</span>
    &lt;<span class="pl-ent">link</span> <span class="pl-e">href</span>=<span class="pl-s"><span class="pl-pds">"</span>css/one.css<span class="pl-pds">"</span></span> <span class="pl-e">rel</span>=<span class="pl-s"><span class="pl-pds">"</span>stylesheet<span class="pl-pds">"</span></span>&gt;
    &lt;<span class="pl-ent">link</span> <span class="pl-e">href</span>=<span class="pl-s"><span class="pl-pds">"</span>css/two.css<span class="pl-pds">"</span></span> <span class="pl-e">rel</span>=<span class="pl-s"><span class="pl-pds">"</span>stylesheet<span class="pl-pds">"</span></span>&gt;
    <span class="pl-c">&lt;!-- endbuild --&gt;</span>
</pre>

   the result not like yours,didn't have the /
<pre>
    &lt;<span class="pl-ent">link</span> <span class="pl-e">rel</span>=<span class="pl-s"><span class="pl-pds">"</span>stylesheet<span class="pl-pds">"</span></span> <span class="pl-e">href</span>=<span class="pl-s"><span class="pl-pds">"</span>css/combined.css<span class="pl-pds">"</span></span>&gt;
</pre>
   yours:
      <pre>
    &lt;<span class="pl-ent">link</span> <span class="pl-e">rel</span>=<span class="pl-s"><span class="pl-pds">"</span>stylesheet<span class="pl-pds">"</span></span> <span class="pl-e">href</span>=<span class="pl-s"><span class="pl-pds">"</span>css/combined.css<span class="pl-pds">"</span></span>/&gt;
</pre>
   I'm use the thymeleaf  Template ,if the link not contain / &gt;,the project would run error.
   How can I solve the problem?
   Thank you!

**Comment by geniuszhe** [comment]
I modify the src ,thanks for your code ~

**Comment by jonkemp** [comment]
This is not supported. Not having the closing forward slash is valid HTML5.
