### ISSUE TITLE
Can't pass absolute path as searchPath

### ISSUE THREAD

**Issue by timdp** [jonkemp/gulp-useref#123]
I was running into an empty stream when passing an absolute path as my `searchPath`. I kind of expected gulp-useref not to fail silently on an empty glob result, but anyway, the reason why it doesn't work is [this call to `path.join()`](https://github.com/jonkemp/gulp-useref/blob/7f7d8d85e8f7c0935c598969ebd02a6cda055ce8/index.js#L15) (and presumably the one a few lines higher too).

Would changing that call to a `path.resolve()` break anything? In my case, it worked fine.

As a workaround, I used `path.relative(__dirname, dir)` to get a relative path, but supporting absolute paths seems like a useful feature.

**Comment by jonkemp** [comment]
You can submit a pull request if you like. :smile:

**Comment by timdp** [comment]
Will do!
