### ISSUE TITLE
reuse same verdor-xxx.{js, css}

### ISSUE THREAD

**Issue by Awakening-j** [jonkemp/gulp-useref#127]
Can `useref` reuse the same builded file instead of re-doing build again?  
I have about 10 files that using the same bower libs, but the gulp build seems too slowly, can `useref` check md5 or anyother symbol to check if is the same vendor file, and reuse it?

**Comment by Awakening-j** [comment]
no one is here????

**Comment by jonkemp** [comment]
Yes someone is here. :smile:  I'm not really sure I understand the question you are asking. There are ways to avoid doing the same things overtime with gulp. Please check these links.

https://github.com/gulpjs/gulp/blob/master/docs/recipes/incremental-builds-with-concatenate.md
https://github.com/gulpjs/gulp/blob/master/docs/recipes/only-pass-through-changed-files.md
https://github.com/gulpjs/gulp/blob/master/docs/recipes/rebuild-only-files-that-change.md

**Comment by Awakening-j** [comment]
Thanks, I will see it.  
My question is I have some files inject same libs,  
for example: a.html, b.html, c.html, they all need same lib: bootstrap, jquery  
Then the md5 of their vender.js/css must be the same,  
So I want to reuse the vender.js/css, not build it three times

**Comment by jonkemp** [comment]
Post your gulpfile. Maybe someone here can help.

**Comment by Awakening-j** [comment]
Very simple requirement, Assume that all my html files require same bower dependencies, and same build path:  scripts/vendor.js, so at present, useref will build same vendor.js many times, override it each time, so how to let it build once and inject `script tag vendor.js` in each html
![2015-08-21 12 40 46](https://cloud.githubusercontent.com/assets/8085088/9401438/163dd578-4802-11e5-9560-76872063048a.png)
![2015-08-21 12 41 03](https://cloud.githubusercontent.com/assets/8085088/9401439/1a3f2bd6-4802-11e5-801c-36538aa8e6ad.png)
![2015-08-21 12 41 44](https://cloud.githubusercontent.com/assets/8085088/9401440/1d79a33a-4802-11e5-9d14-2e6cfb38028c.png)

**Comment by jonkemp** [comment]
You could do that with separate tasks for vendor.js and the html. One task could create the vendor.js and the user task could just update the html. Users can be used that way. It doesn't have to do all of it.

https://github.com/jonkemp/gulp-useref#usage
