### ISSUE TITLE
Add trailing and ending string to src and href attribute

### ISSUE THREAD

**Issue by samhenri** [jonkemp/gulp-useref#129]
I'm creating pages for some sort of template engine in Python. All assets (src and href attributes) must start with `$href('` and end with `')`. Right now using `<!-- build:css -->` and `<!-- build:js -->` are working fine and putting my assets in the right places, but the html template output url's are all absolute or relative paths. Is it possible to change useref "template" for `<script>` and `<link>` tags? For instance:

`    
    <link rel="stylesheet" href="/bower_components/jquery-ui/themes/base/jquery-ui.css">
    
    
    <script src="/bower_components/modernizr/modernizr.js"></script>
    `

... would put the file in libs/themes/base/ folder, but the outputted html would be something like:

`<link rel="stylesheet" href="$href('libs/themes/base/jquery-ui.css')">` instead of `<link rel="stylesheet" href="libs/themes/base/jquery-ui.css">` or `<script src="$href('libs/modernizr.js')"></script>` instead of `<script src="libs/modernizr.js"></script>`

**Comment by jonkemp** [comment]
No, but you could use another step in the task after gulp-useref and use gulp-replace to update the templates.

**Comment by samhenri** [comment]
I tried using gulp-replace-html with no luck, with just two lines and a regex I did it with gulp-replace. Thanks!
