### ISSUE TITLE
What method can add a version number at the back of the file?

### ISSUE THREAD

**Issue by rayliao** [jonkemp/gulp-useref#131]
```
<html>
<head>
    <!-- build:css css/combined.css -->
    <link href="css/one.css" rel="stylesheet">
    <link href="css/two.css" rel="stylesheet">
    <!-- endbuild -->
</head>
<body>
    <!-- build:js scripts/combined.js -->
    <script type="text/javascript" src="scripts/one.js"></script>
    <script type="text/javascript" src="scripts/two.js"></script>
    <!-- endbuild -->
</body>
</html>
```

I want the resulting HTML like this:

```
<html>
<head>
    <link rel="stylesheet" href="css/combined.css?v=20150829"/>
</head>
<body>
    <script src="scripts/combined.js?v=20150829"></script>
</body>
</html>
```

**Comment by jonkemp** [comment]
Here's one way to do it.

https://github.com/yeoman/generator-gulp-webapp/blob/master/docs/recipes/asset-revisioning.md

**Comment by rayliao** [comment]
`gulp-rev` appends content hashes like this:
> unicorn.css → unicorn-d41d8cd98f.css

It change the name of the file, but I can't think of change the file name, is just add the version number：
unicorn.css → unicorn.css?v=d41d8cd98f

**Comment by manuel-di-iorio** [comment]
If you do this with useref, the version hash will be useless, because it will be changed only when you change the file, losing the "no-cache stuff"

One way to do this is to correctly handle the cache with the server but sometimes is not possible, so you could do it yourself.
Example with php: echo "unicorn.css?v=" . strval(microtime(true))

Probably there is an automatic lib that can handle that for you

**Comment by philBrown** [comment]
@jonkemp 

> Here's one way to do it.

That obviously doesn't work with gulp-useref v3

**Comment by jonkemp** [comment]
I submitted a pull request to update that doc last night and it's been merged. I tested that myself and it works. :hand:

**Comment by philBrown** [comment]
@jonkemp thank you very much, that was definitely helpful.

**Comment by OXOYO** [comment]
@jonkemp It`s work. Thanks.

**Comment by henriquechehad** [comment]
Some update about doing:

`unicorn.css → unicorn.css?v=d41d8cd98f`
instead:
`unicorn.css → unicorn-d41d8cd98f.css`
?
