### ISSUE TITLE
multiple blocks, different rules

### ISSUE THREAD

**Issue by vdclouis** [jonkemp/gulp-useref#134]
Hi, is there a way to execute different methods based on a certain identifier?
I would like to do something like this:
```html
<!-- build:js build/pdf.js-->
<script src="vendor/pdfjs/pdf.js"></script>
<!-- endbuild -->

<!-- build:js build/app.js -->
<script src="build/app.js"></script>
<!-- endbuild -->
```

```js
gulp.task('magic', function () {
var assets = useref.assets();

return gulp.src('*.html')
  .pipe(assets)
  .pipe(gulpif('pdf.js', x(), y(), z() )) // <= I need to identify the pdf.js build block somehow
  .pipe(gulpif('app.js', foo())) // <= I need to identify the app.js build block somehow
  .pipe(assets.restore())
  .pipe(useref())
  .pipe(gulp.dest('dist'));
})
```

**Comment by jonkemp** [comment]
Need more info please.

**Comment by vdclouis** [comment]
@jonkemp I need to run different plugins for different build blocks.
But I'm not sure how I can target those build blocks. From the `readme` there's only examples for basic usages like `gulpif('*.css', minify())`. I wonder if I can do something like `gulpif('buildBlockA', minify())` and `gulpif('buildBlockB', concat())`.
I hope this makes sense ^^

**Comment by jonkemp** [comment]
Yes, you should be able to do exactly what you are asking. Is there a problem?
