### ISSUE TITLE
How to specify different relative assets path

### ISSUE THREAD

**Issue by manuel-di-iorio** [jonkemp/gulp-useref#141]
Related to this feature request: https://github.com/jonkemp/gulp-useref/issues/106

I have this folder structure:
    
    app
    ---- js
    -------- script.js
    ---- html
    -------- index.html
    
But instead useref compiles my assets (js) inside the html folder and I'm looking for an option to specify a different relative path for the assets.

useref html block code:
 
    
    <script src="..\js\script1.js" async></script>
    <script src="..\js\script2.js" async></script>
    

Useref correctly replaces the path in the compiled html file of the js assets with /app/js/script.js but as written above, doesn't compile in the correct folder the assets (that is not app/html/app/js/script.js but app/js/script.js).
The option needed should be like "outputRelativePath" of gulp-usemin

Thanks for attention

**Comment by manuel-di-iorio** [comment]
Sorry for bump, is that possible?

**Comment by jonkemp** [comment]
Sure. I'm looking into it.

**Comment by jonkemp** [comment]
Wait, would `transformPath` not work?

https://github.com/jonkemp/gulp-useref#optionstransformpath

**Comment by manuel-di-iorio** [comment]
Isn't `transformPath` applied on the search of the raw assets (so not the compilation) ?

    "in case the path needs to be modified before **search** happens."

**Comment by jonkemp** [comment]
Ah yes, I see.

**Comment by jonkemp** [comment]
There's now a base option to specify the output folder relative to the cwd.

https://github.com/jonkemp/gulp-useref#optionsbase

**Comment by XuJinNet** [comment]
+1 @nathanredblur

**Comment by zce** [comment]
+1 @nathanredblur

**Comment by nathanredblur** [comment]
I fix this, I don't remember well how but I think that was something like this.
```
gulp.task('build:client', () => {
  return gulp.src('dist/server/view/file.jade', {base: 'dist/public'})
      .pipe(useref())
      .pipe(gulp.dest('dist/public'));
});
```

If someone can test and confirm, will be nice.
