### ISSUE TITLE
2.0 is not compatible with 1.3 ?

### ISSUE THREAD

**Issue by copooper** [jonkemp/gulp-useref#142]
When I update to the 2.0 , the old code doesn't work. The error msg is : File not found with singular glob. why ? Thx.

**Comment by jonkemp** [comment]
No it's not, hence the new version number. It throws the error now if you have a bad file path, so you have a bad file path somewhere. This was a change made in the vinyl-fs module.

**Comment by copooper** [comment]
Well ,in my project, the glob.sync function might not return a correct file path array.

**Comment by copooper** [comment]
something like {.tmp/serve,src}, the latter src will be ignored. And in some case ,'{' may be added to the file path incorrectly.

**Comment by jonkemp** [comment]
I'm not sure what you are asking. If you have a specific question or problem, please post a code example.

**Comment by volak** [comment]
I got this error message, the problem was one of the paths in my css bundle was incorrect. 
In the previous version I suppose this was just ignored - now its not.

I don't mind the change but maybe a more helpful error message would be nice :)

**Comment by copooper** [comment]
Yeah, I found it's indeed the bad file path that cause my problem.Sorry for my mistake ,thx.

**Comment by fyrebase** [comment]
Add this at line 113 to easily see which asset is causing the problem.

```
	var fs = require('fs');
	fs.stat(pattern, function(err, stat) {
			if(err) {
				console.log(err);
			}
	});
```

**Comment by jonkemp** [comment]
Can this be closed?

**Comment by fyrebase** [comment]
I would. The question has been answered

**Comment by copooper** [comment]
Of course
