### ISSUE TITLE
opts.searchPath doesn't work as documented

### ISSUE THREAD

**Issue by callumlocke** [jonkemp/gulp-useref#143]
The readme says that opts.searchPath [can be an array](https://github.com/jonkemp/gulp-useref#optionssearchpath).

But when I supply it as an array, [this line](https://github.com/jonkemp/gulp-useref/blob/b2358b81ad761d003f18af6de730033206b53a88/index.js#L101) throws an error (because path.resolve doesn't accept arrays as arguments).

**Comment by jonkemp** [comment]
Are you using version 2.0?

**Comment by callumlocke** [comment]
Yes

**Comment by jonkemp** [comment]
Thanks for letting me know!

**Comment by callumlocke** [comment]
thanks for the quick fix!
