### ISSUE TITLE
upgrade to 3.x breaks old gulp file with useref.assets

### ISSUE THREAD

**Issue by rwillmer** [jonkemp/gulp-useref#153]
You get this error

  TypeError: $.useref.assets is not a function

**Comment by rwillmer** [comment]
I think it would be really useful for the v3 documentation to show the difference between v2 and v3 usage. I'll do a Pull Request if you agree.

The v2.x documentation gives this usage example:

    var gulp = require('gulp'),
        useref = require('gulp-useref');

    gulp.task('default', function () {
      var assets = useref.assets();

      return gulp.src('app/*.html')
        .pipe(assets)
        .pipe(assets.restore())
        .pipe(useref())
        .pipe(gulp.dest('dist'));
    });

The v3.x documentation gives this:

    var gulp = require('gulp'),
      useref = require('gulp-useref');

    gulp.task('default', function () {
      return gulp.src('app/*.html')
        .pipe(useref())
        .pipe(gulp.dest('dist'));
    });

**Comment by rwillmer** [comment]
Here's a link to the old API

https://github.com/jonkemp/gulp-useref/tree/v.2.1.0

**Comment by jonkemp** [comment]
Sure, I think v3 is pretty well documented, but if you would like to add something showing the difference between the two, I'll look at it.

**Comment by NicholasGlazer** [comment]
@rwillmer thanks!
