### ISSUE TITLE
concact not working, files are always concatenated 

### ISSUE THREAD

**Issue by GenZodd** [jonkemp/gulp-useref#157]
This is more of a question but I can't get concact to work. In my dev build I would like to leave them no concatenated but when I do .pipe($.useref({noconcat:true})) it still concats all the files in each section down to one file. 

    
    
    
    
    

After the injects I get this.

    
    
    <script src="../bower_components/jquery/dist/jquery.js"></script>
    <script src="../bower_components/angular/angular.js"></script>
    <script src="../bower_components/angular-resource/angular-resource.js"></script>
    
    

after the useref call I get this. 

     <script src="scripts/vendor.js"></script>

**Comment by jonkemp** [comment]
@GenZodd Which version of the plugin are you using?

**Comment by GenZodd** [comment]
~1.3.0 Sorry should have provided that.

**Comment by jonkemp** [comment]
It should work if you update to the latest version. Be sure to note the updated syntax though.

https://github.com/jonkemp/gulp-useref#usage

**Comment by GenZodd** [comment]
wow I should have realized how far out of date I was. I will ask one more probably dumb question. I have noconcat working but searchPath does not seem to work still. 

    .pipe($.useref({ searchPath: 'src' }))

what I am trying to do is get it to concat only this chunk of JS files.

**Comment by jonkemp** [comment]
Try using `gulp-debug`.

**Comment by jonkemp** [comment]
Can this be closed?
