### ISSUE TITLE
gulp-useref:  undefined is not a function

### ISSUE THREAD

**Issue by spfiedler** [jonkemp/gulp-useref#158]
I have been using gulp-useref 1.0.2 for a long time.  But I have been having some trouble with IE comments being stripped out of my index file.  I seemed to me that updating to a later version of gulp-useref (3.0.x) would be a good idea.  However, when I try this, I get

[12:21:02] TypeError: undefined is not a function

Here the snippet from my gulp file:
...
    var assets = $.useref.assets();

    return gulp.src('src/components/**/*.html')
      .pipe(assets)
...

It fails on the 'var' line

**Comment by jonkemp** [comment]
Please note the new syntax.

https://github.com/jonkemp/gulp-useref#usage

**Comment by rwillmer** [comment]
Related to #153

**Comment by spfiedler** [comment]
OK, thanks, I get that.  However, I am trying to get the IE comments to be included as they are with node-useref, but have been unsuccessful at doing so.  Is that feature include here?

**Comment by jonkemp** [comment]
Yes. It uses the same code.
