### ISSUE TITLE
build:css and build:js not working 

### ISSUE THREAD

**Issue by boyfunky** [jonkemp/gulp-useref#165]
I am trying to concatenate my js and css files but it is not working 

my gulpfile.js 

gulp.task('useref', function (done) {
  gulp.src('./www/templates/**/*.html')
    .pipe(useref())
    .pipe(gulp.dest('./www/dist'))
    .on('end', done);
});

my index.html 
  <head>
    <meta http-equiv="Content-Security-Policy">
    <meta charset="utf-8">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no, width=device-width">
    <title></title>

    <link href="lib/ionic/css/ionic.css" rel="stylesheet">

    
    <link href="css/font-awesome.css" rel="stylesheet">
    <link href="css/style.css" rel="stylesheet">
    <link href="css/select.css" rel="stylesheet">
    <link href="css/ionic.app.css" rel="stylesheet">
    <link href="css/selectize.css" rel="stylesheet">
    
    <link href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" rel="stylesheet"/>
    <link href='https://fonts.googleapis.com/css?family=RobotoDraft:400,500,700,400italic' rel='stylesheet' type='text/css'>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="lib/ionic-material/dist/ionic.material.min.css" rel="stylesheet">
    <link href="lib/ion-autocomplete/dist/ion-autocomplete.css" rel="stylesheet">
    <link href="lib/ionic-toast/src/style.css" rel="stylesheet">

    
    

    

    <script src="lib/ionic/js/ionic.bundle.js"></script>
    <script src="lib/angular-mocks/angular-mocks.js"></script>
    <script src="lib/angular-http-auth/src/http-auth-interceptor.js"></script>
    <script src="lib/angular-ui-router/release/angular-ui-router.js"></script>
    <script src="lib/ui-select/dist/select.js"></script>
    <script src="lib/ion-autocomplete/dist/ion-autocomplete.js"></script>
    <script src="lib/angular_ios9_patch/angular-ios9-uiwebview.patch.js"></script>
    <script src="lib/ionic-material/dist/ionic.material.min.js"></script>
    <script src="lib/angular-filters/dist/angular-filters.js"></script>
    <script src="lib/angular-messages/angular-messages.js"></script>
    <script src="lib/ng-file-upload/ng-file-upload.min.js"></script>
    <script src="lib/ionic-toast/dist/ionic-toast.bundle.min.js"></script>
    <script src="lib/ngstorage/ngStorage.min.js"></script>

    
    <script src="lib/ngCordova/dist/ng-cordova.min.js"></script>
    <script src="cordova.js"></script>

    
    <script src="dist/dist_js/app/app.js"></script>
    <script src="dist/dist_js/app/routes.js"></script>
    <script src="dist/dist_js/app/controllers/controllers.js"></script>
    <script src="dist/dist_js/app/services/services.js"></script>
    <script src="dist/dist_js/app/AppSettings.js"></script>
    <script src="dist/dist_js/app/directives/directives.js"></script>
    <script src="dist/dist_js/app/services/app_start_services.js"></script>
    <script src="dist/dist_js/app/services/authentication_services.js"></script>
    <script src="dist/dist_js/app/services/common_services.js"></script>
    <script src="dist/dist_js/app/services/create_cases_services.js"></script>
    <script src="dist/dist_js/app/services/referral_case_services.js"></script>
    <script src="dist/dist_js/app/services/tokens_services.js"></script>
    <script src="dist/dist_js/app/services/register_users_services.js"></script>
    <script src="dist/dist_js/app/services/save_local_db_services.js"></script>
    <script src="dist/dist_js/app/controllers/app_controller.js"></script>
    <script src="dist/dist_js/app/controllers/main_controller.js"></script>
    <script src="dist/dist_js/app/controllers/new_cases_controller.js"></script>
    <script src="dist/dist_js/app/controllers/referral_controller.js"></script>
    

    
		<script src="dist/dist_js/app/templates.js"></script>
		
  </head>

why doesnt it create the new file styles.css and app.js in the respective folders?

**Comment by jonkemp** [comment]
Can you post the output here? Also, can you try using gulp-debug?

**Comment by boyfunky** [comment]
@jonkemp sorry found out wht my issue was nd solved it. I missed some steps tht was causin the error.

**Comment by evilgeniuscreative** [comment]
@boyfunky Please tell us what the steps were that you missed in case someone else has this issue?

**Comment by kevincote** [comment]
I have the same error can you please tell me what you did?

**Comment by levyadams** [comment]
Hey thanks for telling us what your issue was so other people could maybe use this as a resource! Nice work bro!
