### ISSUE TITLE
Error in README.md for "Transform Streams"

### ISSUE THREAD

**Issue by akrawitz** [jonkemp/gulp-useref#166]
The code example to integrate source maps has an error in it. The line:

    .pipe(useref({}, lazypipe().pipe(sourcemaps.init, { loadMaps: true })()))

should be:

    .pipe(useref({}, lazypipe().pipe(sourcemaps.init, { loadMaps: true })))

Notice that the lazypipe is passed as a function, not invoked.
Thanks!

**Comment by jonkemp** [comment]
Fixed. Thanks for letting me know!

https://github.com/jonkemp/gulp-useref/commit/3e77dfbb89a070b62ed8f7a3ed169f07209b1b2a#diff-04c6e90faac2675aa89e2176d2eec7d8
