### ISSUE TITLE
strip all html instead of build sections

### ISSUE THREAD

**Issue by algebris** [jonkemp/gulp-useref#179]
Hi
I'm trying to process my html with useref 3.0.5 and output looks like
```
<link rel="stylesheet" href="styles/lib.css">
<link rel="stylesheet" href="styles/app.css">
<script src="js/lib.js"></script>
<script src="js/app.js"></script>
```
only 4 lines instead of whole html!

I use this setup
```
return gulp
        .src(config.index)
        .pipe($.plumber())
        .pipe($.useref({searchPath: './'}))
        .pipe($.if('*.css', $.minifyCss()))
        .pipe($.if('*.js', $.uglify()))
        .pipe(gulp.dest(config.build));
```
In previous versions (1.0.*) it works the same manner. I found that after 
`assets.restore()` html file is ok, but after `useref()` it cleaning up my html again ...
I can't understand where i'm wrong.

Thanks

**Comment by algebris** [comment]
I just found it goes like that because of no new lines for every html line (it was just joined together) like
`<div>..</div><div>...</div>`
It would be great to distinguish not only by new lines.
For an instance if i use this code
`</div><!-- build:js js/lib.js -->`
it will never find lib.js section

**Comment by jonkemp** [comment]
So it worked before with no new lines in the html?

**Comment by algebris** [comment]
nope, it seems main logic of useref works "by lines" but not "by chars" when it looks for necessary entities like build section etc.

**Comment by jonkemp** [comment]
Yes, this is correct.

**Comment by algebris** [comment]
thank you for quick answers!
is it possible to improve it?

**Comment by jonkemp** [comment]
Not without rewriting it, as far as I can tell, and I am not inclined to do that right now.

**Comment by jonkemp** [comment]
Related #177.
