### ISSUE TITLE
Jade issue

### ISSUE THREAD

**Issue by THE-Beck** [jonkemp/gulp-useref#203]
I have near 50 jade templates. Which is almost ~35 `.html` file.

With `useref` task takes almost 30min. But without `useref` it takes ~30sec. Is there any issue with this task?

```
gulp.task('views', () => {
  return gulp.src('app/views/*.jade')
    .pipe($.plumber())
    .pipe($.jade({pretty: true}))
    .pipe(gulp.dest('.tmp'))
    .pipe(reload({stream: true}));
});

gulp.task('useref', ['views', 'styles', 'scripts'], () => {
  return gulp.src(['app/*.html', '.tmp/*.html'])
    .pipe($.useref({searchPath: ['.tmp', 'app', '.']}))
    .pipe($.if('*.js', $.uglify()))
    .pipe($.if('*.css', $.cssnano()))
    .pipe(gulp.dest('dist'));
});
```

**Comment by jonkemp** [comment]
What do you mean without useref? The two tasks are very different. The useref task has three prerequisite tasks that run before the task even runs.

**Comment by THE-Beck** [comment]
What i mean is if i remove the `useref` pipe from the `useref` task then it will only take 30sec. But with the `useref` pipe it takes ~30min.

Is there any way around with jade template (jade layout template)? Without searching in compiled thousands of .html files.

**Comment by jonkemp** [comment]
Well, the tests pass, so how does it not work?

**Comment by THE-Beck** [comment]
Sorry, I've mistyped in my jade template.

```
// build:css styles/vendor.css
// endbuild
```
should be
```
//- build:css styles/vendor.css -->
//- endbuild-->
```
