### ISSUE TITLE
Error by combining CSS - please, help

### ISSUE THREAD

**Issue by burkanov** [jonkemp/gulp-useref#211]
Hello, I was trying out gulp-useref according to the tutorial [https://css-tricks.com/gulp-for-beginners/] and got stuck with useref throwing an error when I try to make it to combine 2 CSS files and transfer them from 'app' to 'dist' directory. It works perfectly with JS, but strangely fails with CSS.

**Terminal says:**
Starting 'useref'...
events.js:141
      throw er; // Unhandled 'error' event"

The demo is on GitHub: https://github.com/burkanov/ll24

**Here is my HTML:**
`  <head>
    <meta charset="utf-8">
    <title></title>

    
      <link rel="stylesheet" href="css/test.css">
      <link rel="stylesheet" href="css/more.css">
    

  </head>
  <body>
    hi there
    
      <script type="text/javascript" src="../node_modules/jquery/dist/jquery.js"></script>
      <script type="text/javascript" src="js/main.js"></script>
    
  </body>`

**And that's Gulp:**
`// Reqs
var gulp = require('gulp');
var sass = require('gulp-sass');
var browserSync = require('browser-sync').create();
var useref = require('gulp-useref');
var uglify = require('gulp-uglify');
var gulpIf = require('gulp-if');
var cssnano = require('gulp-cssnano');

// Tasks
gulp.task('useref', function(){
  return gulp.src('app/**/*.html')
    .pipe(useref())
    .pipe(gulpIf('*.js', uglify()))
    .pipe(gulpIf('*.css', cssnano()))
    .pipe(gulp.dest('dist'))
});

gulp.task('sass', function() {
  return gulp.src('app/sass/*.sass')
    .pipe(sass())
    .pipe(gulp.dest('app/css'))
    .pipe(browserSync.reload({
      stream: true
    }))
});

gulp.task('browserSync', function() {
  browserSync.init({
    server: {
      baseDir: 'dist'
    },
  });
});

gulp.task('watch', ['browserSync', 'sass', 'useref'], function(){
  gulp.watch('app/sass/*.sass', ['sass']);
  gulp.watch('app/js/**/*.js', browserSync.reload);
  gulp.watch('app/**/*.html', browserSync.reload);
});
`
Will be very thankful if someone could have a look in my issue...
Thank you!

**Comment by eddiemonge** [comment]
`test.css` is empty. that might explain it

**Comment by jonkemp** [comment]
The problem is in your css build block.

```html
<!-- build:css css/styles.min.js -->
  <link rel="stylesheet" href="css/test.css">
  <link rel="stylesheet" href="css/more.css">
<!-- endbuild -->
```

Because you are telling useref to save your css file with a .js extension, gulpif tries to run the css file through uglify-js and fails. Changing the .js extension to a .css extension looks to me like it solves the issue.
