### ISSUE TITLE
debug mode?

### ISSUE THREAD

**Issue by kiwi1342** [jonkemp/gulp-useref#216]
Hi,

I'm keep getting this error message:

'throw new Error('Invalid glob argument: ' + glob);'

but unfortunately I don't know on which file useref is working to better understand where the error is. Is there any debug mode or is there a method to log the current working file?

thanks

**Comment by jonkemp** [comment]
You could try [gulp-debug](https://github.com/sindresorhus/gulp-debug).

**Comment by kiwi1342** [comment]
thanks it worked perfectly.
