### ISSUE TITLE
cache files?

### ISSUE THREAD

**Issue by kiwi1342** [jonkemp/gulp-useref#217]
Hi,

I'm using useref on multiple pages and all have the same lib tag where I include all js libraries. I also minify all resources each time but after the first time, the lib.js file is already prepared and I don't want to keep working on the same js files.

Is it possible to use the cached files instead of building a js file for each html file?

thanks

**Comment by jonkemp** [comment]
You could try [gulp-cached](https://github.com/contra/gulp-cached).

**Comment by kiwi1342** [comment]
Wow thanks a lot again. There are too many modules to choose from and I really don't know which one is correct for my needs.

Thanks again!
