### ISSUE TITLE
Confused as to the usage of this plugin in regards to new filepaths

### ISSUE THREAD

**Issue by kchima** [jonkemp/gulp-useref#219]
This properly generates concatted/minified

```
styles/vendor.css 
scripts/vendor.js
index.html
```

in my dist directory, but now what?

Do I now need to change my app to use, by default, dist/index.html vs the regular index.html in my home directory? This would be fine, but then it can't seem to find the vendor.js or vendor.css unless I change the html base tag from

```
  <base href="/" />
```

To:

```
  <base href="/dist" />
```

This seems to screw up the other paths/URLs in my angular app, for instance redirecting my home page to:

localhost:8080/dist/posts

instead of:

localhost:8080/posts

Overall I'm just confused by the usage.

**Comment by jonkemp** [comment]
You only run this as part of the build step before going to production. It should replace links to unminified styles and scripts in your html and also generate those styles and scripts for you and put them where you tell it to.

**Comment by kchima** [comment]
Hello Jon, 

Thanks for your quick response. Just to simplify my question a bit,

It copies the new index.html into the Dist directory, along with the scripts and css. 

1) Am I meant to use Dist/index.html as my homepage rather than index.html?

2) Assuming so, it seems to be generating incorrect paths in the index.html. scripts/vendor.js rather than Dist/scripts/vendor.js. Is this a bug or can I configure it to generate the correct path?

**Comment by jonkemp** [comment]
1) Yes, fist is what you would deploy to production. So list/index.html would be your homepage.

2) You can configure it to generate the correct paths.

**Comment by kchima** [comment]
As for your second answer, I'm trying to figure out what configuration to add. Is the extra config in the index.html file (like a base tag) or is it an option for useref?

I assume I need to change how useref generates these paths in the index.html. However, all the options for gulp-useref seem only concerned with inputs, except for base, which doesn't seem to work (overridden by .pipe(gulp.dest('src/main/webapp/dist'))?)

I've spent about 2 nights trying to figure it out without much luck. Even in [your example on the homepage](https://www.npmjs.com/package/gulp-useref#migration-from-v2-api),

        .pipe(gulp.dest('dist'));

results in:

    <script src="scripts/combined.js"></script> 

Shouldn't the generated script src be "dist/scripts/combined.js"?

**Comment by jonkemp** [comment]
The paths come from the comments in the build blocks. Here is an example of what I am talking about.

```html
<html>
<head>
    <!-- build:css css/combined.css -->
    <link href="css/one.css" rel="stylesheet">
    <link href="css/two.css" rel="stylesheet">
    <!-- endbuild -->
</head>
<body>
    <!-- build:js scripts/combined.js -->
    <script type="text/javascript" src="scripts/one.js"></script> 
    <script type="text/javascript" src="scripts/two.js"></script> 
    <!-- endbuild -->
</body>
</html>
```
What do you have there?

**Comment by kchima** [comment]
and 

    

Along with     .pipe(gulp.dest('src/main/webapp/dist'))  generates:

![image](https://cloud.githubusercontent.com/assets/1223934/19177726/b2d37cf6-8c19-11e6-9649-3ad16ae8ddc0.png)

If I change it to:

    
    

Then it generates:
![image](https://cloud.githubusercontent.com/assets/1223934/19177867/f9c47042-8c1a-11e6-87a8-d64921612116.png)

It now has an extra dist folder, dist/dist/scripts/vendor.js.

Of course, I could remove the first 'dist' by changing the gulp configuration to:
.pipe(gulp.dest('src/main/webapp')), and then everything would probably work, but it would overwrite my source index.html.

**Comment by jonkemp** [comment]
Isn't the first result above what you want?

**Comment by kchima** [comment]
No, the issue is that when I change the build:js, the path in the index is dist/scripts/vendor.js, while the script is now located in dist/dist/scripts/vendor.js. It was surprising to me that changing the build:js changes not just the source tag in the index html but the actual output folder for the scripts itself, so there is always an extra dist.

By the way I really appreciate you discussing this with me. 

-Keith

**Comment by jonkemp** [comment]
The way you describe it working is the way it's supposed to work. Let me know if you need anything else.

**Comment by kchima** [comment]
Both the .pipe(gulp.dest('src/main/webapp/dist')) and the build:js control the output folder, gulp.dest doesn't seem to modify the generated source tag to account for adding a gulp.dest. I just don't see any way that the generated source tag could have the correct path unless I put it in the base folder, which would clobber my source index.html.

Is the problem that the paths should be relative but the root of my index.html stays at the root of my workspace? Meaning when it gets

![image](https://cloud.githubusercontent.com/assets/1223934/19192819/88fc5d74-8c75-11e6-86fa-c42906c9cf0b.png)


it's searching for relative paths a directory higher than it should be?

**Comment by jonkemp** [comment]
I still do not see the problem with this.

![image](https://cloud.githubusercontent.com/assets/1223934/19177726/b2d37cf6-8c19-11e6-9649-3ad16ae8ddc0.png)
