### ISSUE TITLE
js absolute path

### ISSUE THREAD

**Issue by carlsummer** [jonkemp/gulp-useref#229]
I would like to use $ {ctx}, do not use ../../, how to amend       
            
        
       
	    <script src="${ctx}/static/plugin/jquery/1.11.3/jquery.min.js"></script>
		<script src="${ctx}/static/javascript/common.js"></script>
		<script src="${ctx}/static/javascript/services/pages.js"></script>
		<script src="${ctx}/static/javascript/customer.js"></script>
	    

	    
	    <script src="${ctx}/static/plugin/jquery/1.11.3/jquery.min.js"></script>
		<script src="${ctx}/static/javascript/common.js"></script>
		<script src="${ctx}/static/javascript/services/pages.js"></script>
		<script src="${ctx}/static/javascript/customer.js"></script>

**Comment by oulaly** [comment]
you got the solution?
