### ISSUE TITLE
Replace deprecated dependency gulp-util

### ISSUE THREAD

**Issue by TheDancingCode** [jonkemp/gulp-useref#245]
[`gulp-util`](https://www.npmjs.com/package/gulp-util) has been recently deprecated. Continuing to use this dependency may prevent the use of your library with the latest release of Gulp 4 so **it is important to replace `gulp-util`**.

The [README.md](https://github.com/gulpjs/gulp-util) lists alternatives for all the components so a simple replacement should be enough.

Your package is one of the most popular packages still relying on `gulp-util`, it would be good to publish a fixed version to npm as soon as possible.

See:
- https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
- https://github.com/gulpjs/gulp-util/issues/143

**Comment by demurgos** [comment]
I see that it was fixed recently:
https://github.com/jonkemp/gulp-useref/commit/81cb43f40f1265fe68beb6c4a7cc7abad0b655a8

@jonkemp 
Could you publish the updated version to _npm_?

**Comment by jonkemp** [comment]
> It’s possible that a plugin using gulp-util isn’t broken if it’s not using the gutil.File API. While not as urgent, the plugin author should still transition away from gulp-util.

Yes, I can publish a new version to npm. It was not urgent however since it was only using `gutil.PluginError` and should work with Gulp 4 even though Gulp 4 has not been released yet.

**Comment by jonkemp** [comment]
Done e388dabebbd528ad7aa7b3b8d7e7c840d3b64f00.

**Comment by demurgos** [comment]
Thank you very much.

Gulp 4 is planned to get a stable release soon that's why we are working on this. It also helps to ensure that the most popular plugins are still actively maintained.
