### ISSUE TITLE
Improve docs for blocks alternate search path

### ISSUE THREAD

**Issue by palmerj** [jonkemp/gulp-useref#246]
Unless I missed something, it would be good to mention in the documentation that the block alternate search path can contain a sequence of paths processed from right to left, using JSON brace array notation e.g:

```js
    <!-- build:js({.,src}) js/lib.js -->
```

Thanks!

**Comment by jonkemp** [comment]
Thanks! If you are interested in adding this to the documentation yourself, a pull request would be welcome. 😄

**Comment by palmerj** [comment]
Thanks. PR #247 created.

**Comment by jonkemp** [comment]
Done 53efa13d6c276be46fabbafdff08f0882c98a9a2.
