### ISSUE TITLE
Add ability to resolve useref dependencies from vinyl stream

### ISSUE THREAD

**Issue by robrich** [jonkemp/gulp-useref#30]
If I'm precompiling the resources (scss/less/coffee/typescript/etc) I have to write these to a temp directory only to be pulled in by useref.  I'd love it if gulp-useref could accept a gulp stream and pick off matching dependencies, avoiding the need to use `.tmp`.  See https://github.com/google/web-starter-kit/blob/master/gulpfile.js#L122

**Comment by noamokman** [comment]
+1

**Comment by jonkemp** [comment]
Should be fixed by #116.
