### ISSUE TITLE
useref.assets() seems to choke when a javascript is from a CDN

### ISSUE THREAD

**Issue by socketwiz** [jonkemp/gulp-useref#37]
I ran into the issue using Web Start Kit and reported it https://github.com/google/web-starter-kit/issues/208 but they asked if I would report it here since the problem is with this package.  Any idea how to work-around this?

**Comment by indolering** [comment]
I'm having issues with CSS that imports fonts from external CDNs (`@import 'https://fonts.googleapis.com/css?family=Open+Sans:400,400i,600';`).

It will work, but my build watcher has led Google to blacklist my IP :cry:.  Not sure what the optimal resolution is, either a regex in the build system or maybe a comment around specific import statements?
