### ISSUE TITLE
How to use this in django template?

### ISSUE THREAD

**Issue by lyuehh** [jonkemp/gulp-useref#48]
Like this:

```
<!-- build:css static/dist/sre.min.css -->
<link rel="stylesheet" type=text/css href="{{url_for('static',filename='css/bootstrap.css')}}">
<link rel="stylesheet" type=text/css href="{{url_for('static',filename='css/bootstrap-theme.css')}}">
<link rel="stylesheet" type=text/css href="{{url_for('static',filename='css/select2.css')}}">
<link rel="stylesheet" type=text/css href="{{url_for('static',filename='css/ng-grid.css')}}">

<!-- endbuild -->
```

**Comment by LRPalacios** [comment]
is there any planning on supporting django templates? 
i have something like

  
    
    <link rel="stylesheet" href="{{ STATIC_URL }}lib/animate.css/animate.css" />
    <link rel="stylesheet" href="{{ STATIC_URL }}lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="{{ STATIC_URL }}lib/fontawesome/css/font-awesome.css" />
    <link rel="stylesheet" href="{{ STATIC_URL }}lib/admin-lte/dist/css/AdminLTE.css" />

**Comment by LRPalacios** [comment]
actually using gulp-replace like [this](http://stackoverflow.com/a/29686204/1685147) you can make it  work
