### ISSUE TITLE
Possible to generate random name?

### ISSUE THREAD

**Issue by liuwenchao** [jonkemp/gulp-useref#52]
Is it possible to generate random name? maybe make it random if no name is assigned:

```
<!-- build:css -->
    <link href="css/one.css" rel="stylesheet">
    <link href="css/two.css" rel="stylesheet">
<!-- endbuild -->
```

or receive a defined name from the build task?

**Comment by JinxiuLee** [comment]
404

**Comment by jonkemp** [comment]
https://github.com/yeoman/generator-gulp-webapp/blob/master/docs/recipes/asset-revisioning.md
