### ISSUE TITLE
End Tag (/) removed from <link>

### ISSUE THREAD

**Issue by sathishk** [jonkemp/gulp-useref#57]
Resubmitting as per Gulp User Suggestion.(https://github.com/gulpjs/gulp/issues/639)

We use HTML 5 based template engine ([Thymeleaf](http://www.thymeleaf.org)), which will use strict mode to validate HTML documents. In short, At run time, they validate whether all HTML tags are closed properly like in XMLs. Consider we have below code inside our HTML

```
<link rel="stylesheet" href="styles/main.css"/>
```

Once I run **gulp build** ( i used [generator-gulp-angular](https://www.npmjs.org/package/generator-gulp-angular)), I noticed that, in the dist folder, the above HTML code becomes

```
<link rel="stylesheet" href="styles/main.css">
```

**without the '/'** at the end which will be considered as unclosed tag.

**Comment by geemang2000** [comment]
This creates issues with template libraries like Thymeleaf that vaild closed tags.  Is there an option to put this back?

**Comment by gnicol-bzh** [comment]
Hi,
I have the same problem using useref with XSL files. They're supposed to generate HTML5 in the end but unfortunately, the XSL/XSLT engine fails each time an HTML5 tag is not closed (even if it's valid HTML5). Let's say I have to generate *"XHTML5"*. I wish I could use an other template engine, but I don't have the choice, I have to use XSL...
Any idea how to use useref with *"XHTML5"* ?

**Comment by volyx** [comment]
+1

**Comment by paolodenti** [comment]
+1

**Comment by nelaturuk** [comment]
+1

**Comment by wattazoum** [comment]
While I agree with @jedmao regarding the HTML5 specs, sometimes reality catches us. I have the same problem with an application using XHTML. 
I found a workaround, using `gulp-replace` and a regexp : 
```
gulp.src(mySrc)
.pipe(useref())
// match the 'non closing' link tag and close it
.pipe(gulpIf('cssimport.xhtml', replace(/(<link [^>]*)(?!\/)>/g, "$1 />") ))
```
