### ISSUE TITLE
please provide support for gulp-sourcemaps

### ISSUE THREAD

**Issue by ryanhaugh** [jonkemp/gulp-useref#64]
What are the chances that support for gulp-sourcemaps can be added?  I need to have the ability to generate a sourcemap that includes the original files (not the concatenated one).

Maybe I can already do this and I just can't figure it out?

**Comment by doxavore** [comment]
Has anyone actually been able to use gulp-sourcemaps with gulp-useref? Are there any working examples someone can point to for this?

The only way I've been able to get it to work is to add this before https://github.com/jonkemp/gulp-useref/blob/58ec1823290a55b62a3a8e6f30bc167bef1b9285/index.js#L116
```javascript
  // outside of loop: var sourcemaps = require('gulp-sourcemaps')
  src.pipe(gulpif(/\.js$/, sourcemaps.init()))
```

If I instrument `gulp-sourcemaps`'s `init()` it only shows it's init'ing the first file when being given in an assets call... this seems like it should be equivalent of the edit above, but it just doesn't work:
```javascript
  var assets = $.useref.assets({}, gulpif(/\.js$/, sourcemaps.init()));
```

**Comment by mvalster** [comment]
I would also be interested to see how you actually implement `gulp-sourcemaps` with using `noconcat` while still achieving the same end result. Currently when passing `noconcat` the files are obviously not concatenated, how does one achieve this afterwards without reaching a high level of complexity?

**Comment by jonkemp** [comment]
Latest commit should resolve this issue.

**Comment by velkumars** [comment]
Hi, 

How to use source maps for useref  for individual js file? before concatenation. below is my code 

gulp.task('optimize', ['inject'], function() {   
    var assets = $.useref.assets({ searchPath: './' });   
    // Filters are named for the gulp-useref path
    var cssFilter = $.filter('**/*.css');
    var jsAppFilter = $.filter('**/' + config.optimized.app);
    var jslibFilter = $.filter('**/' + config.optimized.lib);
    var templateCache = config.temp + config.templateCache.file;
    log("log assets => " + JSON.stringify(assets));
    return gulp
        .src(config.index)
        .pipe($.plumber())
        .pipe(inject(templateCache, 'templates'))
        .pipe(assets) // Gather all assets from the html with useref        
         .pipe(sourcemaps.init())
        // Get the css
        .pipe(cssFilter)
        .pipe($.csso())
        .pipe(cssFilter.restore())
        // Get the custom javascript
        .pipe(jsAppFilter)
        .pipe($.ngAnnotate({ add: true }))
        .pipe($.uglify())
        .pipe(getHeader())
        .pipe(jsAppFilter.restore())
        // Get the vendor javascript
        .pipe(jslibFilter)
        .pipe($.uglify()) // another option is to override wiredep to use min files
        .pipe(jslibFilter.restore())
        // Take inventory of the file names for future rev numbers
        .pipe($.rev())
        // Apply the concat and file replacement with useref
        .pipe(assets.restore())
        .pipe($.useref())
        // Replace the file names in the html with rev numbers
        .pipe($.revReplace())
        .pipe(sourcemaps.write('maps'))
        .pipe(gulp.dest(config.build));
});

**Comment by venkatesan-narasimhan** [comment]
Hi. Is there any working solution available for generating sourcemaps by using userref with noconcat option and then concatenating the script files afterwards?

**Comment by jonkemp** [comment]
I have not tried it but there is an example in the documentation of a solution that may work for you using transform streams.

https://github.com/jonkemp/gulp-useref#transform-streams

**Comment by venkatesan-narasimhan** [comment]
Perfect! Exactly what I needed. Thanks jonkemp.
