### ISSUE TITLE
Searchpath fix broke my build

### ISSUE THREAD

**Issue by guzart** [jonkemp/gulp-useref#80]
Just an FYI, but the search path fix broke my build. I was using the searchpath configuration as a parameter of `useref.assets({ searchPath: '{.tmp,app}')`.

The behaviour before the fix was that it would search for a file first in `.tmp` and then in `app` and use the file what was found first. 

The behaviour after the fix was to include files from both directories.

So in my case I was using `index.js`, and after the fix it would concat `.tmp/index.js` (es5) and `app/index.js` (es6), which would throw an error during minification.

I think this change in behaviour deserved at least a minor version bump.

*Thanks for your work in this awesome plugin.*

**Comment by shinnn** [comment]
I think the previous behavior is more appropriate. People who code HTML don't expect that a single `<script>` tag imports multiple source files. One `<script>` tag means one source.

**Comment by jonkemp** [comment]
@shinnn wasn't it your pull request that changed the behavior?

o_O

**Comment by shinnn** [comment]
> the search path fix broke my build

I thought @guzart referred 16119c133b9db8348de5dc36f5085840dc05eea8.

@guzart Right?

**Comment by jonkemp** [comment]
@shinnn it's probably all one set of changes to him. How would he know? Your pull request switched from getting file paths from glob.sync to using vinyl-fs to handle that. Correct? I tested this outside of the plugin after I merged your code and it was not working the way it was written. I fixed it so that it would work and then refactored it some. So I can't say for sure what caused the change in behavior but it could not have been released as it was.

**Comment by shinnn** [comment]
@jonkemp Ah, I jumped to wrong conclusion. The main cause is the change from using glob to vinyl-fs, as @jonkemp said.

**Comment by yads** [comment]
Just noticed this as an issue with our build as well.

**Comment by jonkemp** [comment]
So, @guzart @yads is this still an issue for you in 1.1.1?

**Comment by yads** [comment]
We downgraded to 1.0.x in the meantime, will try with 1.1.1. When I get a chance.

**Comment by ntrifunovic** [comment]
I have experienced this issue with 1.1.2 .

**Comment by jonkemp** [comment]
Closing. Please use the latest version and report any issues from that.
