### ISSUE TITLE
Possible to use different types?

### ISSUE THREAD

**Issue by robdodson** [jonkemp/gulp-useref#85]
Is it possible to add additional types for the build blocks, for example:

```
<!-- build:html elements/elements.vulcanized.html -->
  <link rel="import" href="elements/elements.html">
<!-- endbuild-->
```

I'd like to do this to support HTML Imports

**Comment by jonkemp** [comment]
I'll mark this as a feature request. Thanks!

**Comment by therealklanni** [comment]
@robdodson I was just looking for how to do the very same.

@jonkemp if you can give me some clues where to start, I can start looking into implementing this.

**Comment by jonkemp** [comment]
@therealklanni probably need to start with the `useref` module which is in a separate repo.

**Comment by therealklanni** [comment]
@jonkemp way ahead of you there. Can you give me some insight with gulp-useref, though?

I'm working on implementing custom blocks in node-useref, and I see that in gulp-useref we directly call that. So my thought was to just pass an `options` object there to useref. I figured `options` can be callbacks by type, such as 

```
useref(input, {
  import: function (importBlocks) {
    // do something with importBlocks (array of useref blocks found matching "build:import")
  }
});
```

So I guess what I need to know about gulp-usemin is what is the best way to handle the options?

**Comment by therealklanni** [comment]
I'm thinking the best way to implement this in node-useref is as follows:

```
<!-- build:import components -->
<link rel="import" href="/bower_components/some/path"></link>
<!-- endbuild -->
```

In this example, for a custom use block, the `path` part of the directive ("components" here) would just be exposed to the handler as such:

```
useref(input, {
  import: function (importBlocks) {
    var components = importBlocks.components.assets; // <-- components here is associated with the `path` in the directive.
  }
});
```

This is just how useref currently constructs the references object, but we can potentially improve on that. Of course, _normally_ that `path` value is just used to later concat all the blocks that were given the same path into a single file. Being that we're adding custom behavior, I thought it was best to leave any concatenation to the handler. useref also allows an "extra attributes" field in the directive, which I think was added specifically to support adding attributes to a tag, but I can generalize this behavior so it can be used as an "additional options" field instead (extra attributes or options, depending on context), allowing more options to be passed to a custom block, if that would be useful to anyone. Maybe that could be where a concat option can be enabled to tell useref to follow the default behavior of concatenating the results into a file?

@robdodson @jonkemp please give me any feedback/suggestions for how you think we can improve the interface.

**Comment by robdodson** [comment]
What you have above looks good to me. Being able to define my own handler is ideal.

**Comment by therealklanni** [comment]
Our team went a different direction, so this is no longer needed for me. If anyone else is interested in adding this, I can still open a PR with my changes. Just leave a comment.

**Comment by therealklanni** [comment]
Slightly different result for the handler signature. See my included documentation for details.

**Comment by therealklanni** [comment]
FYI, my changes to useref have been merged and published as 0.3.9. So someone should be able to add the support for that to gulp-useref now. :metal:

**Comment by bcho** [comment]
How can I pass the customized type settings to useref? Can we pass an `opts` object to `useref` like this? 

```javascript
var useref = require('gulp-useref');

gulp.src('index.html')
  .pipe(useref({import: function(content, target, options) { //... }}));
```

**Comment by therealklanni** [comment]
@bcho yes, exactly. See digisfera/useref#33

**Comment by doconnor78** [comment]
Is it possible for to dynamically provide a filename for the build operations?
After spending some time investigating 'import' I've found that it does not concatenate files in a custom block.. The following is what I am trying to do:

       
	<script src="bower_components/angular/angular.js"></script>
	<script src="bower_components/angular-route/angular-route.js"></script>
	<script src="bower_components/angular-sanitize/angular-sanitize.js"></script>
	<script src="bower_components/angular-cookies/angular-cookies.js"></script>
	

The code resides in a JSP so I am making the code be context root aware.. Today my project layout is:
- app
   -css
   -images
   -js
-dist
   -all minified/compiled code

If I set context root as '/' then I need to add '/dist/' to all my src/hrefs.. I thought I'd be able to handle this via custom blocks but file concatenation does not occur in that case? 

Thoughts?

**Comment by emanuelet** [comment]
Hi,
Has this been implemented in gulp-useref? I could really use it for building my Polymer elements in my Angular 2 app.

Thanks in advance

**Comment by jonkemp** [comment]
@emanuelet which thing are you referring to? Custom blocks are supported it would seem based on the status of this issue.

**Comment by emanuelet** [comment]
I know that they are supported in the _userref_ package but is not clear how to use them in the _gulp-userref_ one.

Forgive my ignorance, I'm pretty sure that is a very simple syntax, but if you can provide me an example that will be wonderful

**Comment by jonkemp** [comment]
A look at the tests gave me an example.

```js
useref({
    custom: function (content, target) {
        return content === 'someContent' ? target : content;
    }
});
```

and the build block looks like this:

```html
<!-- build:custom customResult -->
someContent
<!-- endbuild -->
```

**Comment by emanuelet** [comment]
I knew that it was somewhere. Thanks you so much for the help.

P.S.: I think this should be added to the Readme

**Comment by emanuelet** [comment]
That's how I got it to work

This has to go in the **index.html** (notice the I had to spin-off the Polymer initialisation to its own file)
```html
    <!-- build:js assets/webcomponents.js -->
    <script src="/assets/components/webcomponentsjs/webcomponents.js"></script>
    <!-- endinject -->
    <!-- build:js assets/polymer.js -->
    <script src="/assets/scripts/polymer.js"></script>
    <!-- endinject -->
    <!-- build:custom elements.html -->
    <link rel="import" href="/assets/components/polymer/polymer.html">
    <link rel="import" href="/assets/components/paper-button/paper-button.html">
    <link rel="import" href="/assets/components/paper-input/paper-input.html">
    <!-- endinject -->
```

And this is the change needed in the **build.js**
```javascript
        gulp.src(config.assetsPath.components + '**/*.*', {
                base: config.assetsPath.components
            })
            .pipe(gulp.dest(config.build.assetPath + 'components'));

        gulp.src(config.index)
            .pipe(useref({
                custom: function(content, target) {
                    return content === '/assets/components' ? target : content;
                }
            }))
```

useref is still not able to combine the html files but now it will keep the references instead of stripping them
