### ISSUE TITLE
Keep data-attributes on includes

### ISSUE THREAD

**Issue by bnhovde** [jonkemp/gulp-useref#88]
Hi,

First of all, thanks for all the great work. I use this for most of my projects.

I'm currently working on a project using skrollr stylesheets, which requires the css file to have a data-attribute of data-skrollr-stylesheet. This is stripped out in the post-build css include statement.

Is there a way i can get around this?

**Comment by jonkemp** [comment]
I thought it did already but if it does not you need to make the request in the user repo.

https://github.com/digisfera/useref/issues

**Comment by bnhovde** [comment]
You are absolutely right. I was adding my attributes in the wrong place.

My bad! Keep on truckin!
