### ISSUE TITLE
Missing assets are ignored

### ISSUE THREAD

**Issue by hadrienk** [jonkemp/gulp-useref#89]
The assets are passed to the 'vinyl-fs' src() method. 

I am sure I understand why since the documentation does not state that it is possible to do things like: 
```html
<!-- build:css /css/combined.css -->
<link href="/css/**/*.css" rel="stylesheet">
<!-- endbuild -->

However, this causes problems when files are not found, they are simply ignored.

**Comment by jonkemp** [comment]
I don't really see this as an issue that affects many people. So I'm not interested in accepting your pull request at this time. Thanks.

**Comment by jonkemp** [comment]
Closing as the pull request was merged. The behavior has changed though since vinyl-fs throws an error if the file path is bad. It now emits the error from the stream if there is a bad file path.
