### ISSUE TITLE
Generate source map files

### ISSUE THREAD

**Issue by dragonflypl** [jonkemp/gulp-useref#91]
Hi,

is it possible to configure this plugin so that when js files are concatenated, also a source map file is produced? Something which is done, for instance, by:

https://github.com/mikach/gulp-concat-sourcemap

Thanks

**Comment by jonkemp** [comment]
Support for sourcemaps was added here:

https://github.com/jonkemp/gulp-useref/pull/70

**Comment by jonkemp** [comment]
Try this #115.
