### ISSUE TITLE
outdated lodash - improving performance

### ISSUE THREAD

**Issue by igorlino** [jonkemp/gulp-useref#92]
There is a newer version of lodash (3.3.1) which  improved performance 20-40% overall  by better utilizing the JIT in JavaScript engines, using internal helper functions that avoid optimization disqualifications & increase the likelihood of function inlining.

lodash 3.0.0 is 40%  (1.40x) faster than lodash 2.4.1.

In v3 also introduced were lazily evaluated chaining for massive performance wins in certain scenarios.

Any change to update to the latest release?

**Comment by jonkemp** [comment]
Sure, though the only lodash function this is using is `_.flatten`. Any specific improvements there or is it just overall?

**Comment by igorlino** [comment]
Great. 
Specifics also.   at: https://github.com/lodash/lodash/wiki/Changelog

I think since that version there are quite many. Overall anyway, yes.

**Comment by jonkemp** [comment]
I can update the package.json but you can easily update the dependencies yourself if you are concerned about performance. Thanks!

**Comment by igorlino** [comment]
Oh yes I have done so. Of course, its better to get it from the original library :)

I also made a local try, updating not only that but all possible libraries at:  https://github.com/igorlino/gulp-useref/commit/964e87f2a8ae7f684a20bdb7105ef04c2a37c0cf

The result running the 'gulp test' was:

  18 passing (781ms)
  1 failing

:( seems something does not fit well.

**Comment by jonkemp** [comment]
Just upgraded packages and lodash 3.0 did break the tests. I'm trying to figure out what the problem is but not upgrading for now.

**Comment by jonkemp** [comment]
I found the problem and fixed it. Dependencies have been updated. I will consider this closed.
