### ISSUE TITLE
Bundling resources without a link tag

### ISSUE THREAD

**Issue by Andi-Lo** [jonkemp/gulp-useref#95]
Hi there,

first of all thank you for this gulp package its really handy :+1: 

A short introduction to my problem and my motivation for creating this issue:
In web performance optimization you do something like inline the critical CSS and defer the loading of all other files until the page has loaded. For doing this you need a bit of javascript like this snippet:

```javascript
<script>
  function loadCSS(e,a,g,h){function f(){for(var a,c=0;c<d.length;c++)d[c].href&&-1<d[c].href.indexOf(e)&&(a=!0);a?b.media=g||"all":setTimeout(f)}var b=window.document.createElement("link");a=a||window.document.getElementsByTagName("script")[0];var d=window.document.styleSheets;b.rel="stylesheet";b.href=e;b.media="only x";b.onload=h||function(){};a.parentNode.insertBefore(b,a);f();return b};

  loadCSS( "bower_components/A.css" );
  loadCSS( "assets/B.css" );
  loadCSS("....");
</script>
```

So what I would really like to do is getting my components packed but have a different output. Something like this:

```javascript
/* input */
<script> function....()

/* build:css assets/css/all.min.css */
  loadCSS( "bower_components/A.css" );
  loadCSS( "assets/B.css" );
/* endbuild */
</script>

/* output */ 
<script> function....()

  loadCSS( "assets/css/all.min.css" );
</script>
```

I'm just curious if there is a solution to this problem with this gulp package or you can guide me somewhere else. Thank you

**Comment by LuSimeon** [comment]
:+1: 

Hi,
I need this too. I want to bundle files in a specific directory (e.g : /dist/scripts), but I don't want to generate links in HTML because I manage scripts and styles loading in another file. Is this possible ?
Thanks

**Comment by jonkemp** [comment]
You don't need useref to bundle scripts. There's plenty of gulp packages and workflows to do this.

**Comment by jonkemp** [comment]
Closing.
