### ISSUE TITLE
BUG: gulp-useref is not changing index.html

### ISSUE THREAD

**Issue by pksunkara** [jonkemp/gulp-useref#97]
I am trying to migrate a project from grunt to gulp. I wanted to use `gulp-useref` in the place of ` gulp-usemin`. [This](https://github.com/asm-products/confy-web/blob/gulp/gulpfile.js#L94) is the `useref` task I built. And [This](https://github.com/asm-products/confy-web/blob/gulp/app/index.html#) is the HTML file I am trying to use `gulp-useref` on.

If you look at the `index.html`, I have `app.min.js`, `vendor.min.js`, `app.min.css` and `config.min.js`. When running through useref, all of them are getting created correctly, but the `index.html` is not getting changed at all.

According to your README, the index.html should change.

**Comment by dmnplb** [comment]
I have the same problem. Any solutions or alternatives?

**Comment by Phmager** [comment]
This is a bug, which is happening when there are comments within the index.html injection tags.

**Comment by pksunkara** [comment]
Is that going to be fixed?

**Comment by jonkemp** [comment]
To go about getting it fixed, you should create an issue here.

https://github.com/digisfera/useref

Could you also update the title of this issue so it's accurate now?

**Comment by pksunkara** [comment]
Well actually, those comments inside the injection tags get [removed](https://github.com/asm-products/confy-web/blob/gulp/gulpfile.js#L88) before the useref task so that bug should not affect me.

PS: Using useref in grunt does not give me any problems. The problems exist with gulp-useref.

This is the html file the gulp-useref task gets,

```html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="description" content="Easily manage your software credentials">
	<meta name="keywords" content="Confy,Software Credential,Credentials,Management System,SaaS,Cloud">
	<meta name="google-site-verification" content="h0iOQnQftV3vxd2Z5eYuk9x4wBpS03SM3wqxhsCcIMA" />

	<title>Confy - Easily manage your software credentials</title>

	<link rel="shortcut icon" type="image/png" href="/assets/images/favicon.png"/>

	<!-- build:css(tmp/result) /assets/app.min.css -->
	<link rel="stylesheet" href="/assets/app.css">
	<!-- endbuild -->

	<!-- build:js(tmp/result) /assets/config.min.js -->

		<script src="/config/environment.js"></script>

		<script src="/config/environments/production.js"></script>
	<!-- endbuild -->

	<!-- build:js(tmp/result) /assets/vendor.min.js -->

		<script src="/node_modules/forge-min/forge.min.js"></script>
		<script src="/node_modules/jquery/dist/jquery.min.js"></script>
		<script src="/node_modules/jquery.cookie/jquery.cookie.js"></script>
		<script src="/node_modules/bootstrap/dist/js/bootstrap.min.js"></script>
		<script src="/node_modules/underscore/underscore.js"></script>
		<script src="/node_modules/backbone/backbone.js"></script>
		<script src="/node_modules/backbone-computedfields/lib/backbone.computedfields.min.js"></script>
		<script src="/node_modules/jsoneditor-confy/jsoneditor.min.js"></script>
		<script src="/node_modules/jsoneditor-confy/asset/ace/ace.js"></script>

		<script src="/node_modules/react/dist/react.min.js"></script>
		<script src="/node_modules/almond/almond.js"></script>

	<!-- endbuild -->

	<!-- build:js(tmp/result) /assets/app.min.js -->
		<script src="/assets/app.js"></script>
	<!-- endbuild -->
</head>
<body class="landing">
	<!--[if lt IE 8]>
		<p class="browsehappy">
			You are using an <strong>outdated</strong> browser. Please
			<a href="http://browsehappy.com/">upgrade your browser</a>
			to improve your experience.
		</p>
	<![endif]-->

... MORE ...
```

**Comment by pksunkara** [comment]
Sorry, I am an idiot. I was rewriting over the generated useref html file.
